CREATE DATABASE IF NOT EXISTS tp_contact CHARACTER SET utf8mb4;
USE tp_contact;
CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(150),
  email VARCHAR(200),
  message TEXT,
  image_path VARCHAR(255),
  audio_path VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
